# Generated by Django 5.0.7 on 2024-08-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
