# Generated by Django 5.0.7 on 2024-08-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('nzd', 'New Zealand Dollar'), ('usd', 'US Dollar')], default='nzd', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
