# Generated by Django 5.0.7 on 2024-08-07 23:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_currency_item_item_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='suppliers',
            field=models.ManyToManyField(to='items.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(default='', upload_to='', verbose_name='Product Photo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='urgent',
            field=models.BooleanField(default=False, help_text='is it urgent?', verbose_name='Urgent?'),
        ),
    ]
