# Generated by Django 5.0.7 on 2024-08-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
            preserve_default=False,
        ),
    ]
