# Generated by Django 5.0.7 on 2024-08-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_qty',
            field=models.PositiveIntegerField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
